#!/bin/sh
# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do
sleep 1; done

gap=$(xrdb -query | awk '/^dwm\.gappoh:/{print $2}')
export BAR_WIDTH="100%:-$((gap * 2))px"

# Launch bar
polybar -q --reload main &
